### Import dependencies

In [17]:
import openai
import pandas as pd
import tiktoken
from qdrant_client import QdrantClient, models
from qdrant_client.models import VectorParams, Distance, SparseVectorParams, Modifier,PayloadSchemaType, PointStruct, Document, Prefetch, FusionQuery

In [2]:
from dotenv import load_dotenv

load_dotenv('../../.env')

True

### Create new collection in Qdrant

In [3]:
qdrant_client = QdrantClient(url='http://localhost:6333')

In [4]:
qdrant_client.create_collection(
    collection_name='amazon-reviews-collection-01',
    vectors_config={
        "text-embedding-3-small": VectorParams(size=1536, distance=Distance.COSINE),
    }
)

True

### Set index

In [5]:
qdrant_client.create_payload_index(
    collection_name='amazon-reviews-collection-01',
    field_name='parent_asin',
    field_schema=PayloadSchemaType.KEYWORD
)

UpdateResult(operation_id=2, status=<UpdateStatus.COMPLETED: 'completed'>)

### Embedding functions

In [6]:
def get_embedding(text, model='text-embedding-3-small'):
    response = openai.embeddings.create(
        model=model,
        input=text
    )
    return response.data[0].embedding

In [7]:
def get_embeddings_batch(text_list, model='text-embedding-3-small', batch_size=100):
    if len(text_list) <= batch_size:
        response = openai.embeddings.create(input=text_list, model=model)
        return [embedding.embedding for embedding in response.data]
    
    all_embeddings = []
    counter = 1
    for i in range(0, len(text_list), batch_size):
        batch = text_list[i:i+batch_size]
        response = openai.embeddings.create(input=batch, model=model)
        all_embeddings.extend([embedding.embedding for embedding in response.data])
        print(f"Batch {counter * batch_size} completed of {len(text_list)}")
        counter += 1

    return all_embeddings

#### Read Sampled Data with Amazon items

In [12]:
df_reviews = pd.read_json('../../data/Electronics_recent_2022_2023_has_main_category_ratings_100_sample_1000.jsonl', lines=True)

In [13]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase
0,4,Nixplay 10.1 touch screen digital picture frame,I purchased this digital frame on a treasure t...,[],B096DQF21Z,B0BNXXNBB4,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-29 06:52:30.702,19,True
1,5,Great so far...,"Speedy delivery, great sound and a great warra...",[],B08H1WNYTR,B0C72D4J46,AFANVB6MPHJTCTFOVIEBKLWZ2GVA,2022-07-05 14:40:48.001,0,True
2,5,Set up is not that easy.,Nice looking set but installation instructions...,[],B09XGX1GMJ,B09XGQQ98K,AHACLF2COQQE2V33ZFXQ7THZOJ2Q,2022-09-21 11:26:42.074,0,True
3,2,Waste of money,"Very unhappy with this keyboard, it would slip...",[],B07899MFZ2,B07L5L22ZL,AGYEAZK4OEYF2MSSTGJ5WNJDVZKA,2018-09-29 22:39:47.708,1,True
4,5,Nice,Work great,[],B09JSMNZRG,B09LTX3SQX,AH67BI7JTOFR35HMZYFVOEHM4CPQ,2023-01-11 21:15:08.805,0,True

In [14]:
len(df_reviews)

122840

### Preprocess reviews and count tokens

In [16]:
def preprocess_reviews_data(row):
    return f"{row['title']} {row['text']}"

In [26]:
def count_tokens(row):
    encoding = tiktoken.encoding_for_model("text-embedding-3-small")
    return len(encoding.encode(row['preprocessed_data']))

In [27]:
df_reviews['preprocessed_data'] = df_reviews.apply(preprocess_reviews_data, axis=1)
df_reviews['token_count'] = df_reviews.apply(count_tokens, axis=1)

In [28]:
df_reviews.head()

,rating,title,text,images,asin,parent_asin,user_id,timestamp,helpful_vote,verified_purchase,preprocessed_data,token_count
0,4,Nixplay 10.1 touch screen digital picture frame,I purchased this digital frame on a treasure t...,[],B096DQF21Z,B0BNXXNBB4,AFZUK3MTBIBEDQOPAK3OATUOUKLA,2022-07-29 06:52:30.702,19,True,Nixplay 10.1 touch screen digital picture fram...,255
1,5,Great so far...,"Speedy delivery, great sound and a great warra...",[],B08H1WNYTR,B0C72D4J46,AFANVB6MPHJTCTFOVIEBKLWZ2GVA,2022-07-05 14:40:48.001,0,True,"Great so far... Speedy delivery, great sound a...",27
2,5,Set up is not that easy.,Nice looking set but installation instructions...,[],B09XGX1GMJ,B09XGQQ98K,AHACLF2COQQE2V33ZFXQ7THZOJ2Q,2022-09-21 11:26:42.074,0,True,Set up is not that easy. Nice looking set but ...,18
3,2,Waste of money,"Very unhappy with this keyboard, it would slip...",[],B07899MFZ2,B07L5L22ZL,AGYEAZK4OEYF2MSSTGJ5WNJDVZKA,2018-09-29 22:39:47.708,1,True,Waste of money Very unhappy with this keyboard...,66
4,5,Nice,Work great,[],B09JSMNZRG,B09LTX3SQX,AH67BI7JTOFR35HMZYFVOEHM4CPQ,2023-01-11 21:15:08.805,0,True,Nice Work great,3

In [29]:
len(df_reviews)

122840

In [ ]:
df_reviews = df_reviews[df_reviews['token_count'] < 8192] #this is the max number of tokens for the embedding model to process
len(df_reviews)

122840

In [31]:
total_tokens = df_reviews['token_count'].sum()

In [ ]:
total_tokens #this number times the price per 1M token gives the total cost of the embeddings

np.int64(6506026)

### Add data to Qdrant collection

In [33]:
relevant_columns = ['preprocessed_data', 'parent_asin']
df_data_to_embed = df_reviews[relevant_columns]

In [35]:
data_to_embed = df_data_to_embed.to_dict(orient='records')

In [36]:
text_to_embed = [item['preprocessed_data'] for item in data_to_embed]

In [37]:
embeddings = get_embeddings_batch(text_to_embed)

Batch 100 completed of 122840
Batch 200 completed of 122840
Batch 300 completed of 122840
Batch 400 completed of 122840
Batch 500 completed of 122840
Batch 600 completed of 122840
Batch 700 completed of 122840
Batch 800 completed of 122840
Batch 900 completed of 122840
Batch 1000 completed of 122840
Batch 1100 completed of 122840
Batch 1200 completed of 122840
Batch 1300 completed of 122840
Batch 1400 completed of 122840
Batch 1500 completed of 122840
Batch 1600 completed of 122840
Batch 1700 completed of 122840
Batch 1800 completed of 122840
Batch 1900 completed of 122840
Batch 2000 completed of 122840
Batch 2100 completed of 122840
Batch 2200 completed of 122840
Batch 2300 completed of 122840
Batch 2400 completed of 122840
Batch 2500 completed of 122840
Batch 2600 completed of 122840
Batch 2700 completed of 122840
Batch 2800 completed of 122840
Batch 2900 completed of 122840
Batch 3000 completed of 122840
Batch 3100 completed of 122840
Batch 3200 completed of 122840
Batch 3300 completed of 122840
Batch 3400 completed of 122840
Batch 3500 completed of 122840
Batch 3600 completed of 122840
Batch 3700 completed of 122840
Batch 3800 completed of 122840
Batch 3900 completed of 122840
Batch 4000 completed of 122840
Batch 4100 completed of 122840
Batch 4200 completed of 122840
Batch 4300 completed of 122840
Batch 4400 completed of 122840
Batch 4500 completed of 122840
Batch 4600 completed of 122840
Batch 4700 completed of 122840
Batch 4800 completed of 122840
Batch 4900 completed of 122840
Batch 5000 completed of 122840
Batch 5100 completed of 122840
Batch 5200 completed of 122840
Batch 5300 completed of 122840
Batch 5400 completed of 122840
Batch 5500 completed of 122840
Batch 5600 completed of 122840
Batch 5700 completed of 122840
Batch 5800 completed of 122840
Batch 5900 completed of 122840
Batch 6000 completed of 122840
Batch 6100 completed of 122840
Batch 6200 completed of 122840
Batch 6300 completed of 122840
Batch 6400 completed of 122840
Batch 6500 completed of 122840
Batch 6600 completed of 122840
Batch 6700 completed of 122840
Batch 6800 completed of 122840
Batch 6900 completed of 122840
Batch 7000 completed of 122840
Batch 7100 completed of 122840
Batch 7200 completed of 122840
Batch 7300 completed of 122840
Batch 7400 completed of 122840
Batch 7500 completed of 122840
Batch 7600 completed of 122840
Batch 7700 completed of 122840
Batch 7800 completed of 122840
Batch 7900 completed of 122840
Batch 8000 completed of 122840
Batch 8100 completed of 122840
Batch 8200 completed of 122840
Batch 8300 completed of 122840
Batch 8400 completed of 122840
Batch 8500 completed of 122840
Batch 8600 completed of 122840
Batch 8700 completed of 122840
Batch 8800 completed of 122840
Batch 8900 completed of 122840
Batch 9000 completed of 122840
Batch 9100 completed of 122840
Batch 9200 completed of 122840
Batch 9300 completed of 122840
Batch 9400 completed of 122840
Batch 9500 completed of 122840
Batch 9600 completed of 122840
Batch 9700 completed of 122840
Batch 9800 completed of 122840
Batch 9900 completed of 122840
Batch 10000 completed of 122840
Batch 10100 completed of 122840
Batch 10200 completed of 122840
Batch 10300 completed of 122840
Batch 10400 completed of 122840
Batch 10500 completed of 122840
Batch 10600 completed of 122840
Batch 10700 completed of 122840
Batch 10800 completed of 122840
Batch 10900 completed of 122840
Batch 11000 completed of 122840
Batch 11100 completed of 122840
Batch 11200 completed of 122840
Batch 11300 completed of 122840
Batch 11400 completed of 122840
Batch 11500 completed of 122840
Batch 11600 completed of 122840
Batch 11700 completed of 122840
Batch 11800 completed of 122840
Batch 11900 completed of 122840
Batch 12000 completed of 122840
Batch 12100 completed of 122840
Batch 12200 completed of 122840
Batch 12300 completed of 122840
Batch 12400 completed of 122840
Batch 12500 completed of 122840
Batch 12600 completed of 122840
Batch 12700 completed of 122840
Batch 12800 completed of 122840
Batch 12900 completed of 122840
Batch 13000 completed of 122840
Batch 13100 completed of 122840
Batch 13200 completed of 122840
Batch 13300 completed of 122840
Batch 13400 completed of 122840
Batch 13500 completed of 122840
Batch 13600 completed of 122840
Batch 13700 completed of 122840
Batch 13800 completed of 122840
Batch 13900 completed of 122840
Batch 14000 completed of 122840
Batch 14100 completed of 122840
Batch 14200 completed of 122840
Batch 14300 completed of 122840
Batch 14400 completed of 122840
Batch 14500 completed of 122840
Batch 14600 completed of 122840
Batch 14700 completed of 122840
Batch 14800 completed of 122840
Batch 14900 completed of 122840
Batch 15000 completed of 122840
Batch 15100 completed of 122840
Batch 15200 completed of 122840
Batch 15300 completed of 122840
Batch 15400 completed of 122840
Batch 15500 completed of 122840
Batch 15600 completed of 122840
Batch 15700 completed of 122840
Batch 15800 completed of 122840
Batch 15900 completed of 122840
Batch 16000 completed of 122840
Batch 16100 completed of 122840
Batch 16200 completed of 122840
Batch 16300 completed of 122840
Batch 16400 completed of 122840
Batch 16500 completed of 122840
Batch 16600 completed of 122840
Batch 16700 completed of 122840
Batch 16800 completed of 122840
Batch 16900 completed of 122840
Batch 17000 completed of 122840
Batch 17100 completed of 122840
Batch 17200 completed of 122840
Batch 17300 completed of 122840
Batch 17400 completed of 122840
Batch 17500 completed of 122840
Batch 17600 completed of 122840
Batch 17700 completed of 122840
Batch 17800 completed of 122840
Batch 17900 completed of 122840
Batch 18000 completed of 122840
Batch 18100 completed of 122840
Batch 18200 completed of 122840
Batch 18300 completed of 122840
Batch 18400 completed of 122840
Batch 18500 completed of 122840
Batch 18600 completed of 122840
Batch 18700 completed of 122840
Batch 18800 completed of 122840
Batch 18900 completed of 122840
Batch 19000 completed of 122840
Batch 19100 completed of 122840
Batch 19200 completed of 122840
Batch 19300 completed of 122840
Batch 19400 completed of 122840
Batch 19500 completed of 122840
Batch 19600 completed of 122840
Batch 19700 completed of 122840
Batch 19800 completed of 122840
Batch 19900 completed of 122840
Batch 20000 completed of 122840
Batch 20100 completed of 122840
Batch 20200 completed of 122840
Batch 20300 completed of 122840
Batch 20400 completed of 122840
Batch 20500 completed of 122840
Batch 20600 completed of 122840
Batch 20700 completed of 122840
Batch 20800 completed of 122840
Batch 20900 completed of 122840
Batch 21000 completed of 122840
Batch 21100 completed of 122840
Batch 21200 completed of 122840
Batch 21300 completed of 122840
Batch 21400 completed of 122840
Batch 21500 completed of 122840
Batch 21600 completed of 122840
Batch 21700 completed of 122840
Batch 21800 completed of 122840
Batch 21900 completed of 122840
Batch 22000 completed of 122840
Batch 22100 completed of 122840
Batch 22200 completed of 122840
Batch 22300 completed of 122840
Batch 22400 completed of 122840
Batch 22500 completed of 122840
Batch 22600 completed of 122840
Batch 22700 completed of 122840
Batch 22800 completed of 122840
Batch 22900 completed of 122840
Batch 23000 completed of 122840
Batch 23100 completed of 122840
Batch 23200 completed of 122840
Batch 23300 completed of 122840
Batch 23400 completed of 122840
Batch 23500 completed of 122840
Batch 23600 completed of 122840
Batch 23700 completed of 122840
Batch 23800 completed of 122840
Batch 23900 completed of 122840
Batch 24000 completed of 122840
Batch 24100 completed of 122840
Batch 24200 completed of 122840
Batch 24300 completed of 122840
Batch 24400 completed of 122840
Batch 24500 completed of 122840
Batch 24600 completed of 122840
Batch 24700 completed of 122840
Batch 24800 completed of 122840
Batch 24900 completed of 122840
Batch 25000 completed of 122840
Batch 25100 completed of 122840
Batch 25200 completed of 122840
Batch 25300 completed of 122840
Batch 25400 completed of 122840
Batch 25500 completed of 122840
Batch 25600 completed of 122840
Batch 25700 completed of 122840
Batch 25800 completed of 122840
Batch 25900 completed of 122840
Batch 26000 completed of 122840
Batch 26100 completed of 122840
Batch 26200 completed of 122840
Batch 26300 completed of 122840
Batch 26400 completed of 122840
Batch 26500 completed of 122840
Batch 26600 completed of 122840
Batch 26700 completed of 122840
Batch 26800 completed of 122840
Batch 26900 completed of 122840
Batch 27000 completed of 122840
Batch 27100 completed of 122840
Batch 27200 completed of 122840
Batch 27300 completed of 122840
Batch 27400 completed of 122840
Batch 27500 completed of 122840
Batch 27600 completed of 122840
Batch 27700 completed of 122840
Batch 27800 completed of 122840
Batch 27900 completed of 122840
Batch 28000 completed of 122840
Batch 28100 completed of 122840
Batch 28200 completed of 122840
Batch 28300 completed of 122840
Batch 28400 completed of 122840
Batch 28500 completed of 122840
Batch 28600 completed of 122840
Batch 28700 completed of 122840
Batch 28800 completed of 122840
Batch 28900 completed of 122840
Batch 29000 completed of 122840
Batch 29100 completed of 122840
Batch 29200 completed of 122840
Batch 29300 completed of 122840
Batch 29400 completed of 122840
Batch 29500 completed of 122840
Batch 29600 completed of 122840
Batch 29700 completed of 122840
Batch 29800 completed of 122840
Batch 29900 completed of 122840
Batch 30000 completed of 122840
Batch 30100 completed of 122840
Batch 30200 completed of 122840
Batch 30300 completed of 122840
Batch 30400 completed of 122840
Batch 30500 completed of 122840
Batch 30600 completed of 122840
Batch 30700 completed of 122840
Batch 30800 completed of 122840
Batch 30900 completed of 122840
Batch 31000 completed of 122840
Batch 31100 completed of 122840
Batch 31200 completed of 122840
Batch 31300 completed of 122840
Batch 31400 completed of 122840
Batch 31500 completed of 122840
Batch 31600 completed of 122840
Batch 31700 completed of 122840
Batch 31800 completed of 122840
Batch 31900 completed of 122840
Batch 32000 completed of 122840
Batch 32100 completed of 122840
Batch 32200 completed of 122840
Batch 32300 completed of 122840
Batch 32400 completed of 122840
Batch 32500 completed of 122840
Batch 32600 completed of 122840
Batch 32700 completed of 122840
Batch 32800 completed of 122840
Batch 32900 completed of 122840
Batch 33000 completed of 122840
Batch 33100 completed of 122840
Batch 33200 completed of 122840
Batch 33300 completed of 122840
Batch 33400 completed of 122840
Batch 33500 completed of 122840
Batch 33600 completed of 122840
Batch 33700 completed of 122840
Batch 33800 completed of 122840
Batch 33900 completed of 122840
Batch 34000 completed of 122840
Batch 34100 completed of 122840
Batch 34200 completed of 122840
Batch 34300 completed of 122840
Batch 34400 completed of 122840
Batch 34500 completed of 122840
Batch 34600 completed of 122840
Batch 34700 completed of 122840
Batch 34800 completed of 122840
Batch 34900 completed of 122840
Batch 35000 completed of 122840
Batch 35100 completed of 122840
Batch 35200 completed of 122840
Batch 35300 completed of 122840
Batch 35400 completed of 122840
Batch 35500 completed of 122840
Batch 35600 completed of 122840
Batch 35700 completed of 122840
Batch 35800 completed of 122840
Batch 35900 completed of 122840
Batch 36000 completed of 122840
Batch 36100 completed of 122840
Batch 36200 completed of 122840
Batch 36300 completed of 122840
Batch 36400 completed of 122840
Batch 36500 completed of 122840
Batch 36600 completed of 122840
Batch 36700 completed of 122840
Batch 36800 completed of 122840
Batch 36900 completed of 122840
Batch 37000 completed of 122840
Batch 37100 completed of 122840
Batch 37200 completed of 122840
Batch 37300 completed of 122840
Batch 37400 completed of 122840
Batch 37500 completed of 122840
Batch 37600 completed of 122840
Batch 37700 completed of 122840
Batch 37800 completed of 122840
Batch 37900 completed of 122840
Batch 38000 completed of 122840
Batch 38100 completed of 122840
Batch 38200 completed of 122840
Batch 38300 completed of 122840
Batch 38400 completed of 122840
Batch 38500 completed of 122840
Batch 38600 completed of 122840
Batch 38700 completed of 122840
Batch 38800 completed of 122840
Batch 38900 completed of 122840
Batch 39000 completed of 122840
Batch 39100 completed of 122840
Batch 39200 completed of 122840
Batch 39300 completed of 122840
Batch 39400 completed of 122840
Batch 39500 completed of 122840
Batch 39600 completed of 122840
Batch 39700 completed of 122840
Batch 39800 completed of 122840
Batch 39900 completed of 122840
Batch 40000 completed of 122840
Batch 40100 completed of 122840
Batch 40200 completed of 122840
Batch 40300 completed of 122840
Batch 40400 completed of 122840
Batch 40500 completed of 122840
Batch 40600 completed of 122840
Batch 40700 completed of 122840
Batch 40800 completed of 122840
Batch 40900 completed of 122840
Batch 41000 completed of 122840
Batch 41100 completed of 122840
Batch 41200 completed of 122840
Batch 41300 completed of 122840
Batch 41400 completed of 122840
Batch 41500 completed of 122840
Batch 41600 completed of 122840
Batch 41700 completed of 122840
Batch 41800 completed of 122840
Batch 41900 completed of 122840
Batch 42000 completed of 122840
Batch 42100 completed of 122840
Batch 42200 completed of 122840
Batch 42300 completed of 122840
Batch 42400 completed of 122840
Batch 42500 completed of 122840
Batch 42600 completed of 122840
Batch 42700 completed of 122840
Batch 42800 completed of 122840
Batch 42900 completed of 122840
Batch 43000 completed of 122840
Batch 43100 completed of 122840
Batch 43200 completed of 122840
Batch 43300 completed of 122840
Batch 43400 completed of 122840
Batch 43500 completed of 122840
Batch 43600 completed of 122840
Batch 43700 completed of 122840
Batch 43800 completed of 122840
Batch 43900 completed of 122840
Batch 44000 completed of 122840
Batch 44100 completed of 122840
Batch 44200 completed of 122840
Batch 44300 completed of 122840
Batch 44400 completed of 122840
Batch 44500 completed of 122840
Batch 44600 completed of 122840
Batch 44700 completed of 122840
Batch 44800 completed of 122840
Batch 44900 completed of 122840
Batch 45000 completed of 122840
Batch 45100 completed of 122840
Batch 45200 completed of 122840
Batch 45300 completed of 122840
Batch 45400 completed of 122840
Batch 45500 completed of 122840
Batch 45600 completed of 122840
Batch 45700 completed of 122840
Batch 45800 completed of 122840
Batch 45900 completed of 122840
Batch 46000 completed of 122840
Batch 46100 completed of 122840
Batch 46200 completed of 122840
Batch 46300 completed of 122840
Batch 46400 completed of 122840
Batch 46500 completed of 122840
Batch 46600 completed of 122840
Batch 46700 completed of 122840
Batch 46800 completed of 122840
Batch 46900 completed of 122840
Batch 47000 completed of 122840
Batch 47100 completed of 122840
Batch 47200 completed of 122840
Batch 47300 completed of 122840
Batch 47400 completed of 122840
Batch 47500 completed of 122840
Batch 47600 completed of 122840
Batch 47700 completed of 122840
Batch 47800 completed of 122840
Batch 47900 completed of 122840
Batch 48000 completed of 122840
Batch 48100 completed of 122840
Batch 48200 completed of 122840
Batch 48300 completed of 122840
Batch 48400 completed of 122840
Batch 48500 completed of 122840
Batch 48600 completed of 122840
Batch 48700 completed of 122840
Batch 48800 completed of 122840
Batch 48900 completed of 122840
Batch 49000 completed of 122840
Batch 49100 completed of 122840
Batch 49200 completed of 122840
Batch 49300 completed of 122840
Batch 49400 completed of 122840
Batch 49500 completed of 122840
Batch 49600 completed of 122840
Batch 49700 completed of 122840
Batch 49800 completed of 122840
Batch 49900 completed of 122840
Batch 50000 completed of 122840
Batch 50100 completed of 122840
Batch 50200 completed of 122840
Batch 50300 completed of 122840
Batch 50400 completed of 122840
Batch 50500 completed of 122840
Batch 50600 completed of 122840
Batch 50700 completed of 122840
Batch 50800 completed of 122840
Batch 50900 completed of 122840
Batch 51000 completed of 122840
Batch 51100 completed of 122840
Batch 51200 completed of 122840
Batch 51300 completed of 122840
Batch 51400 completed of 122840
Batch 51500 completed of 122840
Batch 51600 completed of 122840
Batch 51700 completed of 122840
Batch 51800 completed of 122840
Batch 51900 completed of 122840
Batch 52000 completed of 122840
Batch 52100 completed of 122840
Batch 52200 completed of 122840
Batch 52300 completed of 122840
Batch 52400 completed of 122840
Batch 52500 completed of 122840
Batch 52600 completed of 122840
Batch 52700 completed of 122840
Batch 52800 completed of 122840
Batch 52900 completed of 122840
Batch 53000 completed of 122840
Batch 53100 completed of 122840
Batch 53200 completed of 122840
Batch 53300 completed of 122840
Batch 53400 completed of 122840
Batch 53500 completed of 122840
Batch 53600 completed of 122840
Batch 53700 completed of 122840
Batch 53800 completed of 122840
Batch 53900 completed of 122840
Batch 54000 completed of 122840
Batch 54100 completed of 122840
Batch 54200 completed of 122840
Batch 54300 completed of 122840
Batch 54400 completed of 122840
Batch 54500 completed of 122840
Batch 54600 completed of 122840
Batch 54700 completed of 122840
Batch 54800 completed of 122840
Batch 54900 completed of 122840
Batch 55000 completed of 122840
Batch 55100 completed of 122840
Batch 55200 completed of 122840
Batch 55300 completed of 122840
Batch 55400 completed of 122840
Batch 55500 completed of 122840
Batch 55600 completed of 122840
Batch 55700 completed of 122840
Batch 55800 completed of 122840
Batch 55900 completed of 122840
Batch 56000 completed of 122840
Batch 56100 completed of 122840
Batch 56200 completed of 122840
Batch 56300 completed of 122840
Batch 56400 completed of 122840
Batch 56500 completed of 122840
Batch 56600 completed of 122840
Batch 56700 completed of 122840
Batch 56800 completed of 122840
Batch 56900 completed of 122840
Batch 57000 completed of 122840
Batch 57100 completed of 122840
Batch 57200 completed of 122840
Batch 57300 completed of 122840
Batch 57400 completed of 122840
Batch 57500 completed of 122840
Batch 57600 completed of 122840
Batch 57700 completed of 122840
Batch 57800 completed of 122840
Batch 57900 completed of 122840
Batch 58000 completed of 122840
Batch 58100 completed of 122840
Batch 58200 completed of 122840
Batch 58300 completed of 122840
Batch 58400 completed of 122840
Batch 58500 completed of 122840
Batch 58600 completed of 122840
Batch 58700 completed of 122840
Batch 58800 completed of 122840
Batch 58900 completed of 122840
Batch 59000 completed of 122840
Batch 59100 completed of 122840
Batch 59200 completed of 122840
Batch 59300 completed of 122840
Batch 59400 completed of 122840
Batch 59500 completed of 122840
Batch 59600 completed of 122840
Batch 59700 completed of 122840
Batch 59800 completed of 122840
Batch 59900 completed of 122840
Batch 60000 completed of 122840
Batch 60100 completed of 122840
Batch 60200 completed of 122840
Batch 60300 completed of 122840
Batch 60400 completed of 122840
Batch 60500 completed of 122840
Batch 60600 completed of 122840
Batch 60700 completed of 122840
Batch 60800 completed of 122840
Batch 60900 completed of 122840
Batch 61000 completed of 122840
Batch 61100 completed of 122840
Batch 61200 completed of 122840
Batch 61300 completed of 122840
Batch 61400 completed of 122840
Batch 61500 completed of 122840
Batch 61600 completed of 122840
Batch 61700 completed of 122840
Batch 61800 completed of 122840
Batch 61900 completed of 122840
Batch 62000 completed of 122840
Batch 62100 completed of 122840
Batch 62200 completed of 122840
Batch 62300 completed of 122840
Batch 62400 completed of 122840
Batch 62500 completed of 122840
Batch 62600 completed of 122840
Batch 62700 completed of 122840
Batch 62800 completed of 122840

In [39]:
len(embeddings)

122840

### Add vectors to Qdrant

In [40]:
point_structs = []
i = 1
for embedding, data in zip(embeddings, data_to_embed):
    point_structs.append(
        PointStruct(
            id=i,
            vector={
                "text-embedding-3-small": embedding
            },
            payload=data
        )
    )
    i += 1

In [41]:
batch_size = 500
counter = 1
for i in range(0, len(point_structs), batch_size):
    batch = point_structs[i:i + batch_size]
    qdrant_client.upsert(
        collection_name='amazon-reviews-collection-01',
        points=batch,
        wait=True
    )
    print(f"Batch {counter * batch_size} completed of {len(point_structs)}")
    counter += 1

Batch 500 completed of 122840
Batch 1000 completed of 122840
Batch 1500 completed of 122840
Batch 2000 completed of 122840
Batch 2500 completed of 122840
Batch 3000 completed of 122840
Batch 3500 completed of 122840
Batch 4000 completed of 122840
Batch 4500 completed of 122840
Batch 5000 completed of 122840
Batch 5500 completed of 122840
Batch 6000 completed of 122840
Batch 6500 completed of 122840
Batch 7000 completed of 122840
Batch 7500 completed of 122840
Batch 8000 completed of 122840
Batch 8500 completed of 122840
Batch 9000 completed of 122840
Batch 9500 completed of 122840
Batch 10000 completed of 122840
Batch 10500 completed of 122840
Batch 11000 completed of 122840
Batch 11500 completed of 122840
Batch 12000 completed of 122840
Batch 12500 completed of 122840
Batch 13000 completed of 122840
Batch 13500 completed of 122840
Batch 14000 completed of 122840
Batch 14500 completed of 122840
Batch 15000 completed of 122840
Batch 15500 completed of 122840
Batch 16000 completed of 122840
Batch 16500 completed of 122840
Batch 17000 completed of 122840
Batch 17500 completed of 122840
Batch 18000 completed of 122840
Batch 18500 completed of 122840
Batch 19000 completed of 122840
Batch 19500 completed of 122840
Batch 20000 completed of 122840
Batch 20500 completed of 122840
Batch 21000 completed of 122840
Batch 21500 completed of 122840
Batch 22000 completed of 122840
Batch 22500 completed of 122840
Batch 23000 completed of 122840
Batch 23500 completed of 122840
Batch 24000 completed of 122840
Batch 24500 completed of 122840
Batch 25000 completed of 122840
Batch 25500 completed of 122840
Batch 26000 completed of 122840
Batch 26500 completed of 122840
Batch 27000 completed of 122840
Batch 27500 completed of 122840
Batch 28000 completed of 122840
Batch 28500 completed of 122840
Batch 29000 completed of 122840
Batch 29500 completed of 122840
Batch 30000 completed of 122840
Batch 30500 completed of 122840
Batch 31000 completed of 122840
Batch 31500 completed of 122840
Batch 32000 completed of 122840
Batch 32500 completed of 122840
Batch 33000 completed of 122840
Batch 33500 completed of 122840
Batch 34000 completed of 122840
Batch 34500 completed of 122840
Batch 35000 completed of 122840
Batch 35500 completed of 122840
Batch 36000 completed of 122840
Batch 36500 completed of 122840
Batch 37000 completed of 122840
Batch 37500 completed of 122840
Batch 38000 completed of 122840
Batch 38500 completed of 122840
Batch 39000 completed of 122840
Batch 39500 completed of 122840
Batch 40000 completed of 122840
Batch 40500 completed of 122840
Batch 41000 completed of 122840
Batch 41500 completed of 122840
Batch 42000 completed of 122840
Batch 42500 completed of 122840
Batch 43000 completed of 122840
Batch 43500 completed of 122840
Batch 44000 completed of 122840
Batch 44500 completed of 122840
Batch 45000 completed of 122840
Batch 45500 completed of 122840
Batch 46000 completed of 122840
Batch 46500 completed of 122840
Batch 47000 completed of 122840
Batch 47500 completed of 122840
Batch 48000 completed of 122840
Batch 48500 completed of 122840
Batch 49000 completed of 122840
Batch 49500 completed of 122840
Batch 50000 completed of 122840
Batch 50500 completed of 122840
Batch 51000 completed of 122840
Batch 51500 completed of 122840
Batch 52000 completed of 122840
Batch 52500 completed of 122840
Batch 53000 completed of 122840
Batch 53500 completed of 122840
Batch 54000 completed of 122840
Batch 54500 completed of 122840
Batch 55000 completed of 122840
Batch 55500 completed of 122840
Batch 56000 completed of 122840
Batch 56500 completed of 122840
Batch 57000 completed of 122840
Batch 57500 completed of 122840
Batch 58000 completed of 122840
Batch 58500 completed of 122840
Batch 59000 completed of 122840
Batch 59500 completed of 122840
Batch 60000 completed of 122840
Batch 60500 completed of 122840
Batch 61000 completed of 122840
Batch 61500 completed of 122840
Batch 62000 completed of 122840
Batch 62500 completed of 122840
Batch 63000 completed of 122840
Batch 63500 completed of 122840
Batch 64000 completed of 122840
Batch 64500 completed of 122840
Batch 65000 completed of 122840
Batch 65500 completed of 122840
Batch 66000 completed of 122840
Batch 66500 completed of 122840
Batch 67000 completed of 122840
Batch 67500 completed of 122840
Batch 68000 completed of 122840
Batch 68500 completed of 122840
Batch 69000 completed of 122840
Batch 69500 completed of 122840
Batch 70000 completed of 122840
Batch 70500 completed of 122840
Batch 71000 completed of 122840
Batch 71500 completed of 122840
Batch 72000 completed of 122840
Batch 72500 completed of 122840
Batch 73000 completed of 122840
Batch 73500 completed of 122840
Batch 74000 completed of 122840
Batch 74500 completed of 122840
Batch 75000 completed of 122840
Batch 75500 completed of 122840
Batch 76000 completed of 122840
Batch 76500 completed of 122840
Batch 77000 completed of 122840
Batch 77500 completed of 122840
Batch 78000 completed of 122840
Batch 78500 completed of 122840
Batch 79000 completed of 122840
Batch 79500 completed of 122840
Batch 80000 completed of 122840
Batch 80500 completed of 122840
Batch 81000 completed of 122840
Batch 81500 completed of 122840
Batch 82000 completed of 122840
Batch 82500 completed of 122840
Batch 83000 completed of 122840
Batch 83500 completed of 122840
Batch 84000 completed of 122840
Batch 84500 completed of 122840
Batch 85000 completed of 122840
Batch 85500 completed of 122840
Batch 86000 completed of 122840
Batch 86500 completed of 122840
Batch 87000 completed of 122840
Batch 87500 completed of 122840
Batch 88000 completed of 122840
Batch 88500 completed of 122840
Batch 89000 completed of 122840
Batch 89500 completed of 122840
Batch 90000 completed of 122840
Batch 90500 completed of 122840
Batch 91000 completed of 122840
Batch 91500 completed of 122840
Batch 92000 completed of 122840
Batch 92500 completed of 122840
Batch 93000 completed of 122840
Batch 93500 completed of 122840
Batch 94000 completed of 122840
Batch 94500 completed of 122840
Batch 95000 completed of 122840
Batch 95500 completed of 122840
Batch 96000 completed of 122840
Batch 96500 completed of 122840
Batch 97000 completed of 122840
Batch 97500 completed of 122840
Batch 98000 completed of 122840
Batch 98500 completed of 122840
Batch 99000 completed of 122840
Batch 99500 completed of 122840
Batch 100000 completed of 122840
Batch 100500 completed of 122840
Batch 101000 completed of 122840
Batch 101500 completed of 122840
Batch 102000 completed of 122840
Batch 102500 completed of 122840
Batch 103000 completed of 122840
Batch 103500 completed of 122840
Batch 104000 completed of 122840
Batch 104500 completed of 122840
Batch 105000 completed of 122840
Batch 105500 completed of 122840
Batch 106000 completed of 122840
Batch 106500 completed of 122840
Batch 107000 completed of 122840
Batch 107500 completed of 122840
Batch 108000 completed of 122840
Batch 108500 completed of 122840
Batch 109000 completed of 122840
Batch 109500 completed of 122840
Batch 110000 completed of 122840
Batch 110500 completed of 122840
Batch 111000 completed of 122840
Batch 111500 completed of 122840
Batch 112000 completed of 122840
Batch 112500 completed of 122840
Batch 113000 completed of 122840
Batch 113500 completed of 122840
Batch 114000 completed of 122840
Batch 114500 completed of 122840
Batch 115000 completed of 122840
Batch 115500 completed of 122840
Batch 116000 completed of 122840
Batch 116500 completed of 122840
Batch 117000 completed of 122840
Batch 117500 completed of 122840
Batch 118000 completed of 122840
Batch 118500 completed of 122840
Batch 119000 completed of 122840
Batch 119500 completed of 122840
Batch 120000 completed of 122840
Batch 120500 completed of 122840
Batch 121000 completed of 122840
Batch 121500 completed of 122840
Batch 122000 completed of 122840
Batch 122500 completed of 122840
Batch 123000 completed of 122840

### Function to run search against reviews on a prefiltered set of product IDs

In [42]:
def retrieve_prefiltered_reviews_data(query, parent_asins, collection_name='amazon-reviews-collection-01', k=5):
    query_embedding = get_embedding(query)

    results = qdrant_client.query_points(
        collection_name=collection_name,
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=models.Filter(
                    must=[
                        models.FieldCondition(
                            key="parent_asin",
                            match=models.MatchAny(any=parent_asins)
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion='rrf'),
        limit=k
    )

    return results

In [48]:
reviews = retrieve_prefiltered_reviews_data(query='bad quality', parent_asins=['B09Q5TNDHY'])

In [49]:
reviews.points

[ScoredPoint(id=62005, version=127, score=0.5, payload={'preprocessed_data': 'Its a total waste and the screen came as if it was used before The screen unlike the picture is so small and when i took it out of the box it looks like the watch was used before its not new<br />wouldn’t recommend', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=47673, version=98, score=0.33333334, payload={'preprocessed_data': 'Not worth the money Watch stopped working after four months.', 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=62009, version=127, score=0.25, payload={'preprocessed_data': "It's junk didn't last more then a week Screen totally blanket out. Don't waste your money", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=80491, version=163, score=0.2, payload={'preprocessed_data': "Its stopped working It's not that durable", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None),
 ScoredPoint(id=105619, version=214, score=0.16666667, payload={'preprocessed_data': "Didn't work I don't know if this product was defective or if it's a poor design or whatever. I'll be sending it back right away. I got it fully charged set up ,<br />went swimming, it worked during the swimming. But afterwards it cease to function and begin to act strangely vibrating almost continually.", 'parent_asin': 'B09Q5TNDHY'}, vector=None, shard_key=None, order_value=None)]

### Define the reviews retrieval tool

In [54]:
def get_embedding(text, model='text-embedding-3-small'):
    response = openai.embeddings.create(
        model=model,
        input=text,
    )
    
    return response.data[0].embedding

def retrieve_prefiltered_reviews_data(query, parent_asins, collection_name='amazon-reviews-collection-01', k=5):
    query_embedding = get_embedding(query)
    qdrant_client = QdrantClient(url="http://localhost:6333")

    results = qdrant_client.query_points(
        collection_name=collection_name,
        prefetch=[
            Prefetch(
                query=query_embedding,
                using="text-embedding-3-small",
                filter=models.Filter(
                    must=[
                        models.FieldCondition(
                            key="parent_asin",
                            match=models.MatchAny(any=parent_asins)
                        )
                    ]
                ),
                limit=20
            )
        ],
        query=FusionQuery(fusion='rrf'),
        limit=k
    )

    retrieved_context_ids = []
    retrieved_context_texts = []
    similarity_scores = []

    for result in results.points:
        retrieved_context_ids.append(result.payload['parent_asin'])
        retrieved_context_texts.append(result.payload['preprocessed_data'])
        similarity_scores.append(result.score)
    return {
        'retrieved_context_ids': retrieved_context_ids,
        'retrieved_context_texts': retrieved_context_texts,
        'similarity_scores': similarity_scores
    }

def process_context(retrieve_context):
    formatted_context = ''

    for id, chunk in zip(retrieve_context['retrieved_context_ids'], retrieve_context['retrieved_context_texts']):
        formatted_context += f"- Product ID: {id}, Product Review: {chunk}\n"

    return formatted_context

def get_formatted_reviews_context(query: str, parent_asins: list[str], top_k: int = 5) -> str:
    """
    Get the top_k reviews matching a query for a list of prefiltered items.
    Args:
        query: The query to get the top k reviews for
        parent_asins: The list of item IDs to prefilter for before running the query
        top_k: The number of reviews to retrieve, this should be at least 20 if multiple items are being filtered
    Returns:
        A string of the top_k context chunks with IDs and average ratings prepeding each chunk, each representing an inventory item for a given query
    """

    retrieved_context = retrieve_prefiltered_reviews_data(query, parent_asins, k=top_k)

    formatted_context = process_context(retrieved_context)

    return formatted_context

In [55]:
reviews = get_formatted_reviews_context(query='bad quality', parent_asins=['B09Q5TNDHY'])

In [57]:
print(reviews)

- Product ID: B09Q5TNDHY, Product Review: Its a total waste and the screen came as if it was used before The screen unlike the picture is so small and when i took it out of the box it looks like the watch was used before its not new<br />wouldn’t recommend
- Product ID: B09Q5TNDHY, Product Review: Not worth the money Watch stopped working after four months.
- Product ID: B09Q5TNDHY, Product Review: It's junk didn't last more then a week Screen totally blanket out. Don't waste your money
- Product ID: B09Q5TNDHY, Product Review: Its stopped working It's not that durable
- Product ID: B09Q5TNDHY, Product Review: Didn't work I don't know if this product was defective or if it's a poor design or whatever. I'll be sending it back right away. I got it fully charged set up ,<br />went swimming, it worked during the swimming. But afterwards it cease to function and begin to act strangely vibrating almost continually.